### ISSUE TITLE
hwpe-tb simulation stuck in loop

### ISSUE THREAD

**Issue by HarshitSharm-a** [pulp-platform/hwpe-tb#2]
I tried running standalone testbench and simulation gets stuck in loop.

![stuck_in_loop](https://user-images.githubusercontent.com/48988347/88390142-18161b80-cdb8-11ea-8392-db67687b5d94.png)

Reference to issue pulp-platform/pulpissimo#143

Thanks in advance.

**Comment by aledolme** [comment]
Hi! Have you found a way to solve this issue? 
Thanks

**Comment by FrancescoConti** [comment]
Might have been caused by erroneous version of hwpe-ctrl. Should work fine now

**Comment by aledolme** [comment]
Hello. I was having the same troubles during the simulation. 
Are now the instructions in the section **Getting Started** of the README file still valid in order to correctly run the testbench?

Thanks in advance.

**Comment by FrancescoConti** [comment]
I updated it to use a different IP management tool (bender instead of ipstools), but the flow is overall very similar. I suggest you remove the content of the `hw/ips` directory though (or start from a clean repo), as its content is managed in a different way.
