### ISSUE TITLE
How to generate the simulation waveform?

### ISSUE THREAD

**Issue by zealshah29** [pulp-platform/hwpe-tb#4]
Hello, so I cloned the hwpe-tb project and followed the steps mentioned in README. 
I can see the following simulation output:
![hwpe-tb questa](https://github.com/pulp-platform/hwpe-tb/assets/75566085/a42de52d-4d21-4ba6-b04e-d1bb7619c78d)

It shows no data as an output for the tcdm data, address etc. 

I want to observe the waveform of all the input and output streams for the hwpe-mac-engine (as shown in the following master thesis: "Design of a Flexible Hardware Accelerator for Ultra-Low Power Quantized Neural Networks based on Serial Multipliers")
![image](https://github.com/pulp-platform/hwpe-tb/assets/75566085/87c31090-b949-48da-b9db-93b14487a3dc)

Can I get some guidance on how can I generate it? Thank you.
@FrancescoConti

**Comment by FrancescoConti** [comment]
You have to run the simulation, see a few tutorials on QuestaSim https://www.google.com/search?q=questasim+tutorial
